replicaCount: 2

image:
  repository: "products-manager-backend"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

environment:
  DB_HOST: "products-manager-db-service"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "adminpassword"
  DB_NAME: "products_db"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 80