apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-manager-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-manager-db
  template:
    metadata:
      labels:
        app: products-manager-db
    spec:
      containers:
        - name: db
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.environment.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.environment.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: {{ .Values.environment.POSTGRES_DB }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: products-manager-db-pvc