apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-manager-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
