apiVersion: v1
kind: Service
metadata:
  name: products-manager-db-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: products-manager-db
