apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-manager-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: products-manager-frontend
  template:
    metadata:
      labels:
        app: products-manager-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}