apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-manager-frontend-ingress
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0].path }}
            pathType: {{ .Values.ingress.hosts[0].paths[0].pathType }}
            backend:
              service:
                name: products-manager-frontend-service
                port:
                  number: {{ .Values.service.port }}
