apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
  selector:
    app: monitoring
